---
title: "WNBA Expansion Draft and Salary Analysis"
format: revealjs
---


## How does the WNBA expansion draft work?

* Held when a new team joins the league  
* Purpose: Allows expansion teams to select players from existing teams  

   * Each existing team can **protect up to 6 players** on their roster  
   * Unprotected players are eligible to be drafted  

* Expansion can select no more than **one player per existing team**  

* Usually takes place in the **offseason before the expansion team's debut**

## Data

* Salary data sourced from Her Hoops Data
* Player statistics sourced from Basketball Reference

##

```{r}
#| echo: false
#| fig-width: 10
#| fig-height: 6

#Source the plot function
source("eda-salary-plot.R")

# Draw the plot
make_salary_plot2()
```


## Methods

* Model building to predict players' expected salary as a function of their in-game statistics

* Compare to their actual 2025 salaries to identify undervalued, "underrated" players

* Build 


## Next steps...

* Model selection 

* Variable selection




